# Language Philosophy 

In [3]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Numpy

Core library for computations, specifically, it allows creating arrays and doing operations on them. Arrays are n-dimensional objects of the same data type.

In [5]:
import numpy as np #common way to call this library

### 1D and 2D arrays

Create a 1-dimentional array.

In [25]:
my_1D_array = np.array([1, 2, 3])

Print it out.

In [27]:
my_1D_array

array([ 1, 22,  3])

Check if it is an array by typing

In [8]:
type(my_1D_array)

numpy.ndarray

Check the dimensions of the array.

In [9]:
my_1D_array.shape

(3,)

Let the second entry of the array to be 22 (hint: remember that indexes start at zero in Python). 

In [26]:
my_1D_array[1] = 22

Create a 2-dimentional array.

In [16]:
my_2D_array = np.array([[1, 2, 3],[4, 5, 6]])

Print it out.

In [30]:
my_2D_array

array([[ 1,  2,  3],
       [ 4, 22,  6]])

See what transpose() function or .T do to your 2D array.

In [22]:
my_2D_array.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
my_2D_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Check if it is an array by typing

In [20]:
type(my_2D_array)

numpy.ndarray

Check the dimensions of the array.

In [21]:
my_2D_array.shape

(2, 3)

Let the row with index 1 and column with index 1 of the array to be 22.

In [29]:
my_2D_array[1,1] = 22

Create 2D array with shape (3, 7).

In [31]:
my_2D_array = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21]])

Check if the shape is correct

In [32]:
my_2D_array.shape

(3, 7)

In [33]:
my_2D_array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Slicing 

Slice your array (create a subarray) consisting of the first 2 rows and first 2 columns. The shape of new  array should be (2, 2).

In [35]:
my_2D_array[:2, :2]

array([[1, 2],
       [8, 9]])

Slice your array (create a subarray) consisting of the last 2 rows and the last 5 columns. The shape of new  array should be (2, 5).

In [42]:
my_2D_array[[1,2], 2:]

array([[10, 11, 12, 13, 14],
       [17, 18, 19, 20, 21]])

In [45]:
my_2D_array[1:3, 2:]

array([[10, 11, 12, 13, 14],
       [17, 18, 19, 20, 21]])

Slicing with Booleans

In [85]:
boolean_mask = (my_2D_array > 5)   
boolean_mask

array([[False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [88]:
my_2D_array[boolean_mask] #notice it converted 2D array into 1D array!

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

You can do it in one shot.

In [89]:
my_2D_array[(my_2D_array > 5)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

### Initializing arrays

Explore fast ways to initialize different types of arrays.

a) array of zeros of shape (10,10), data type should be floats:

In [56]:
array_of_zeros_floats = np.zeros(shape = (10,10))
array_of_zeros_floats

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

b) array of zeros of shape (7,7), data type should be integers:

In [58]:
array_of_zeros_integers = np.zeros(shape = (7,7), dtype=int)
array_of_zeros_integers

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

c) array of ones of shape (7,7), data type should be floats:

In [62]:
array_of_zeros_ones = np.ones((7,7))
array_of_zeros_ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

d) array of random numbers of shape (5, 10) between 0 and 1:

In [72]:
array_of_random_numbers = np.random.random((3, 3))
array_of_random_numbers

array([[0.38088535, 0.24901642, 0.34342887],
       [0.96421254, 0.67383089, 0.11455884],
       [0.5621281 , 0.26106578, 0.15684942]])

e) array of random integers of shape (5, 10) between 0 and 100:

In [83]:
np.random.choice(np.arange(100), (5, 10), replace=True)

array([[27, 49, 25, 33,  4, 83, 51, 77, 19, 35],
       [16, 71, 10, 17, 77, 88, 76, 29, 95, 85],
       [64, 98,  9, 25, 21, 76, 11, 78, 62, 18],
       [91,  7, 59, 37, 25, 23, 88, 48, 40, 75],
       [69, 13, 44, 92, 18, 20, 20,  9, 58, 59]])

Check what arange() is doing

In [84]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Elementwise operations on arrays

In [94]:
first_array = np.array([[1, 2, 3],[4, 5, 6]])
second_array = np.array([[7, 8, 9],[10, 11, 12]])
print(first_array, '\n','\n', second_array)

[[1 2 3]
 [4 5 6]] 
 
 [[ 7  8  9]
 [10 11 12]]


One array and one constant

In [99]:
first_array * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

One array and one function

In [100]:
np.sqrt(first_array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Note that sum function behaves differently.

In [102]:
np.sum(first_array)

21

In [103]:
np.sum(first_array, axis=0) #applies to every column

array([5, 7, 9])

In [104]:
np.sum(first_array, axis=1) #applies to every row

array([ 6, 15])

#### Two arrays

a) sum:

In [95]:
first_array + second_array

array([[ 8, 10, 12],
       [14, 16, 18]])

b) difference:

In [96]:
first_array - second_array

array([[-6, -6, -6],
       [-6, -6, -6]])

c) product:

In [97]:
first_array * second_array

array([[ 7, 16, 27],
       [40, 55, 72]])

d) division:

In [98]:
first_array / second_array

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

# Your Own Functions

In [105]:
def multiply_by_three(x):
    """
    This function multiplys the input by 3
    ---
    Input: Numerical
    Output: Numerical
    """
    return 3*x

In [106]:
multiply_by_three(3)

9

In [162]:
phone_dict = {'Mike': '555-122-363', 
             'Peter': '888-111-344',
             'Jane': '888-333-666',
             'Kate': '667-524-567'}
phone_dict

{'Mike': '555-122-363',
 'Peter': '888-111-344',
 'Jane': '888-333-666',
 'Kate': '667-524-567'}

In [160]:
def get_all_area_numbers(area_code, phone_dict=phone_dict):
    """
    This function finds all numbers by area_code from the dictionary phone_dict
    ---
    Input: Numerical, Dictionary
    Output: Dictionary
    """
    
    new_dict = {}
    for name, number in phone_dict.items():
        if number[:3] == str(area_code):
            my_list.append(number)
            new_dict[name] = number
        
    return new_dict

In [161]:
get_all_area_numbers(area_code=888, phone_dict=phone_dict)

{'Peter': '888-111-344', 'Jane': '888-333-666'}